flow:
  nl: 10
  hm: [4,4]
  batch_norm: true
  prior_dist: 'normal'

training:
  epochs: 150
  batch_size: 256

optim:
  weight_decay: 0.00005
  optimizer: "Adam"
  lr: 0.0005 
  beta1: 0.9
  amsgrad: false
  scheduler: true


