flow:
  nl: 4
  hm: [4,6,6,4]
  batch_norm: true
  prior_dist: 'normal'

training:
  epochs: 80
  batch_size: 64

optim:
  weight_decay: 0.00005
  optimizer: "Adam"
  lr: 0.005 
  beta1: 0.9
  amsgrad: false
  scheduler: true


